name: openclassrooms

services:
  postgres_db:
    image: postgres:15
    container_name: 4_deploy_ml_model
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_password_123
      POSTGRES_DB: futurisys_db
    ports:
      - "5432:5432"
    volumes:
      - openclassrooms_postgres_data:/var/lib/postgresql/data

  # 2. L'INTERFACE GRAPHIQUE (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_OCR
    restart: always
    environment:
      # Tes identifiants pour te connecter à l'interface web de pgAdmin
      PGADMIN_DEFAULT_EMAIL: admin@ocr.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # On l'expose sur le port 5050 pour éviter les conflits
    depends_on:
      - postgres_db # S'assure que la BDD démarre avant pgAdmin      

volumes:
  openclassrooms_postgres_data: